import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from "next/link";
import {useRouter} from "next/router";

export default function Home() {
    const router=useRouter();

    const handleClick=()=>{
router.push('/product')
    }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>

home page
            <button onClick={handleClick}>place order</button>
        </div>
      </main>
    </>
  )
}
